/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Ian Lucas. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

namespace Deathmatch;

public static class Config
{
    public static void ExecDeathmatch() =>
        Runtime.Core.Engine.ExecuteCommand([
            "sv_hibernate_when_empty 0",
            "bot_join_after_player 0",
            "mp_warmuptime 0",
            "mp_warmup_online_enabled 0",
            "mp_roundtime 60",
            "mp_roundtime_defuse 60",
            "mp_respawn_immunitytime -1",
            "mp_dm_healthshot_killcount 0",
            "mp_dm_time_between_bonus_min 3630",
            "mp_dm_time_between_bonus_max 3630",
            "mp_buytime 3630",
            "mp_buy_anywhere 1",
            "mp_buy_during_immunity 0",
            "bot_difficulty 4",
            "mp_bot_ai_bt \"addons/swiftlys2/plugins/ArcfragDeathmatch/resources/configs/bt_default.kv3\"",
            "bot_autodifficulty_threshold_high 0.0",
            "bot_autodifficulty_threshold_low -2.0",
            "bot_chatter off",
            "bot_defer_to_human_goals 0",
            "bot_defer_to_human_items 1",
            "bot_quota 12",
            "bot_quota_mode fill_with_minimum",
            "cash_player_bomb_defused 0",
            "cash_player_bomb_planted 0",
            "cash_player_damage_hostage 0",
            "cash_player_interact_with_hostage 0",
            "cash_player_killed_enemy_default 0",
            "cash_player_killed_enemy_factor 0",
            "cash_player_killed_hostage 0",
            "cash_player_killed_teammate 0",
            "cash_player_rescued_hostage 0",
            "cash_team_elimination_bomb_map 0",
            "cash_team_elimination_hostage_map_t 0",
            "cash_team_elimination_hostage_map_ct 0",
            "cash_team_hostage_alive 0",
            "cash_team_hostage_interaction 0",
            "cash_team_loser_bonus 0",
            "cash_team_loser_bonus_consecutive_rounds 0",
            "cash_team_planted_bomb_but_defused 0",
            "cash_team_rescued_hostage 0",
            "cash_team_terrorist_win_bomb 0",
            "cash_team_win_by_defusing_bomb 0",
            "cash_team_win_by_hostage_rescue 0",
            "cash_team_win_by_time_running_out_bomb 0",
            "cash_team_win_by_time_running_out_hostage 0",
            "ff_damage_reduction_bullets 0.0",
            "ff_damage_reduction_grenade 0.0",
            "ff_damage_reduction_grenade_self 0",
            "ff_damage_reduction_other 0.0",
            "mp_afterroundmoney 0",
            "mp_death_drop_defuser 0",
            "mp_death_drop_grenade 0",
            "mp_death_drop_gun 0",
            "mp_defuser_allocation 0",
            "mp_force_pick_time 15",
            "mp_forcecamera 0",
            "mp_freezetime 0",
            "mp_friendlyfire 1",
            "mp_win_panel_display_time 1",
            "mp_halftime 0",
            "mp_match_can_clinch 0",
            "mp_maxmoney 0",
            "mp_maxrounds 0",
            "mp_playercashawards 0",
            "mp_startmoney 10000",
            "mp_teamcashawards 0",
            "mp_timelimit 10",
            "mp_weapons_allow_zeus 0",
            "mp_weapons_allow_typecount -1",
            "spec_freeze_time 2",
            "sv_talk_enemy_living 1",
            "sv_talk_enemy_dead 1",
            "sv_deadtalk 1",
            "sv_ignoregrenaderadio 1",
            "mp_randomspawn 1",
            "mp_randomspawn_los 1",
            "tv_delay 30",
            "ammo_grenade_limit_flashbang 1",
            "ammo_grenade_limit_total 3",
            "mp_weapons_allow_map_placed 0",
            "mp_weapons_glow_on_ground 0",
            "mp_weapons_allow_zeus -1",
            "mp_display_kill_assists 1",
            "mp_respawn_on_death_t 1",
            "mp_respawn_on_death_ct 1",
            "mp_ct_default_melee weapon_knife",
            "mp_ct_default_secondary weapon_hkp2000",
            "mp_ct_default_primary \"\"",
            "mp_t_default_melee weapon_knife",
            "mp_t_default_secondary weapon_glock",
            "mp_t_default_primary \"\"",
            "mp_default_team_winner_no_objective -1",
            "mp_buy_allow_grenades 0",
            "mp_teammates_are_enemies 1",
            "mp_solid_teammates 1",
            "sv_max_deathmatch_respawns_per_tick 1",
            "sv_disconnected_players_cleanup_delay 15",
            "r_decals_overide_fadestarttime_params 20",
            "mp_limitteams 0",
            "sv_gameinstructor_enable 0",
            "mp_promoted_item_enabled 0",
            "sv_allow_annotations_access_level 0",
            "mp_t_default_secondary \"\"",
            "mp_ct_default_secondary \"\"",
            "mp_give_player_c4 0",
            "sv_warmup_to_freezetime_delay 0",
            "sv_disable_radar 1",
            "sv_minimum_desired_chicken_count 0",
        ]);
}
